### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by dronecz** [cheton/cnc#40]
Hi, 

first of all, many thanks for very nice SW. 

I would like to translate UI to my language, but I can not find right file where I can make some changes. 

Could you tell me where I should look? 

Many thanks.

**Comment by cheton** [comment]
Thanks for asking! Current [i18n resources files](https://github.com/cheton/cnc/blob/master/src/web/i18n/en/resource.json) were using pre-generated hash keys, I felt it's not easy for human to compare keys between two languages without using a translation tool. I will make some changes to i18n resources files to make it easy to translate.

**Comment by cheton** [comment]
Hi @dronecz,

I have updated the resource file for all supported languages, it should be more easily for translations. For examples:
- English: https://github.com/cheton/cnc/blob/master/src/web/i18n/en/resource.json#L150
- French: https://github.com/cheton/cnc/blob/master/src/web/i18n/fr/resource.json#L150
- German: https://github.com/cheton/cnc/blob/master/src/web/i18n/de/resource.json#L150

First, check out [contributions guide](https://github.com/cheton/cnc/blob/master/CONTRIBUTING.md#localization-l10n) and install [v1.2.4](https://github.com/cheton/cnc/releases/tag/v1.2.4). You can do [runtime translations](https://github.com/cheton/cnc/blob/master/CONTRIBUTING.md#runtime-translations) with Google Chrome browser. Once you have finished your translations, copy translated `resource.json` file to `src/web/i18n/{{lng}}/resource.json` in [your forked project](https://github.com/cheton/cnc/blob/master/CONTRIBUTING.md#code-contributions), and create a pull request to submit changes. Thanks.

**Comment by dronecz** [comment]
Hi @cheton 

I did upgrade from 1.2.1 to 1.2.4 on my virtual Ubuntu and tryed translate part of english file to my language and refresher my webpage but nothing changed. I also restarted server but still no change on webpage. I´m probably doing something wrong, but i have no idea what. 

For test I made changes in installed version of cnc: ~/.npm/lib/node_modules/cncjs/src/web/i18n/en .

![git](https://cloud.githubusercontent.com/assets/16454728/16078451/5eb93764-32ff-11e6-8b2f-64ff3f7c707f.PNG)

Many thanks for help.

**Comment by cheton** [comment]
Try making changes to the `~/.npm/lib/node_modules/cncjs/dist/web/i18n/{{lng}}/resource.json` file, and make sure the `[v] Disable cache (while DevTools is open)` option is checked with respect to your Developer Toools settings.

**Comment by dronecz** [comment]
I´m editing file directly so I´m not using browser. When I edit resource.json in this location, it works. 

Many thanks for now.

**Comment by cheton** [comment]
Great! Thank you for your hard work.

**Comment by cheton** [comment]
I may change a little bit by adjusting table and button styles for some widgets (e.g. Axes and G-code widgets) to make the UI layout consistent while translating to other languages.

**Comment by dronecz** [comment]
Hi @cheton 

I made neceserry changes to resource.json and I followed instructions in contribution guide, but I´m not able to push my changes to my branch. I´m newbe with github so please be patient with me.

I got this error when I try to push to git: 
![error](https://cloud.githubusercontent.com/assets/16454728/16150909/524df568-349a-11e6-92c2-98251600550a.PNG)

Many thanks for adwise.

**Comment by cheton** [comment]
You can send the file to cheton@gmail.com. This is a straightforward approach. :smiley:

**Comment by dronecz** [comment]
Ok, here it is ;-).



2016-06-17 15:15 GMT+02:00 Cheton Wu <notifications@github.com>:

**Comment by cheton** [comment]
I didn't receive your mail from my mailbox. Can you try to send it again? Thanks.

**Comment by dronecz** [comment]
Second try ;-)



2016-06-17 15:26 GMT+02:00 Miroslav Zuzelka <mzuzelka@gmail.com>:

**Comment by cheton** [comment]
Sorry for bothering again. There might be some problems that I still cannot find it from my mailbox (cheton@gmail.com). Can you copy/paste your resource.json file at here, I will help move your file to a proper location.

**Comment by dronecz** [comment]
Hi @cheton 

my email probably falling in to spam :-(. Here is zip file ;-).

[cs.zip](https://github.com/cheton/cnc/files/321675/cs.zip)

Many thanks

**Comment by cheton** [comment]
Got it! I will save these files to the `src/web/i18n/cs/` directory. Thanks!

**Comment by cheton** [comment]
There is another one that needs your help. How do you say `Loading...` in Czech?

![image](https://cloud.githubusercontent.com/assets/447801/16170313/6ba61756-3581-11e6-8c51-38e07c5c31fe.png)

The source file is located in https://github.com/cheton/cnc/blob/master/src/app/i18n/cs/resource.json.

**Comment by dronecz** [comment]
Hi,

I feel realy happy that I can contribute to this project.

We say : Nahrávám..

I was thinking hoe to change it but after that I give up bacause word
Loading is very often seen in games, DVDs, TV and really everythink which
needs to load something ;-)

Anyway, thank you very much for your great work.

Miroslav

P.S. I got few ideas about UI of your project, should I fill those in Issue
section of github or can I write to email and send it to you?

2016-06-18 12:25 GMT+02:00 Cheton Wu <notifications@github.com>:

**Comment by cheton** [comment]
Thanks a lot! You can post issues on GitHub that will be much easier to track. :)

**Comment by cheton** [comment]
I will close the issue now. You can update here any time if you need to correct translations.
