### ISSUE TITLE
Helvetica Neue ♦♦♦♦ css declared in 404

### ISSUE THREAD

**Issue by minithc** [cheton/cnc#45]
It seems like Helvetica Neue font, declared in the 404.hogan, provides a limited char set. I finally disabled the css with DevTools, and it is ok now, and I can't repeat the issue. But at one moment, the screen ♦♦♦♦ ♦♦♦♦, ♦♦ ♦ have to disable css fonts to see the text. Used 1251 and UTF-8 code pages in locale.json, both the same result. I will try to repeat the issue anyway.

**Comment by cheton** [comment]
You don't need to change `locale.json` since the file is not currently used in the code. Here is the screenshot in Russian language running with my local development server (in English).

![image](https://cloud.githubusercontent.com/assets/447801/16169969/20445924-3574-11e6-8e2f-3cb8e9eedcb9.png)

**Comment by minithc** [comment]
Thanks! Everything seems to be fine. It was probably my mistake or something with code pages. Thanks again for your time.

**Comment by cheton** [comment]
Thank you for your great efforts. I will publish a release containing newly translated languages (e.g. German, Russian, andTraditional Chinese) in the next few days.
