### ISSUE TITLE
Enhancement: Login to server

### ISSUE THREAD

**Issue by dronecz** [cheton/cnc#47]
Hi @cheton 

I think would be good have some user management to connect and control the server. I´m using Octoprint and there I have to login to control my 3D printer. I think this is good feature because, nobody wil mess up with printer if they don´t know login name. 

Thanks

**Comment by cheton** [comment]
The account management is almost finished and it will be available in 1.8.0 release. Stay tuned for further updates.

### Sign in page
![image](https://cloud.githubusercontent.com/assets/447801/20375688/ac07a524-acbb-11e6-9525-746c3422a137.png)

### Settings > Account
![image](https://cloud.githubusercontent.com/assets/447801/20375707/d036adbe-acbb-11e6-8b3f-514c06e7c9e4.png)

**Comment by dronecz** [comment]
Hi, 

many thanks for this feature. Can I ask if you plan any permissions for users? Like if someone is loged in, this user can control machine and if user is not loged in user can just see we isnterface. 

Many thanks for info and great work ;-).

**Comment by cheton** [comment]
Yeah! There will be a separate UI or read-only mode for anonymous or guest users. Thank you for your suggestion.
