### ISSUE TITLE
Brazilian Portuguese (pt-br) Translate

### ISSUE THREAD

**Issue by cmsteinBR** [cheton/cnc#62]
Hi @cheton , 
First, thank you very much for your awesome work. This translation may need some enhancement.
[pt-br.zip](https://github.com/cheton/cnc/files/433933/pt-br.zip)

**Comment by cheton** [comment]
Thank you for your contribution. I will add Portuguese language later.

**Comment by cheton** [comment]
It's been added in v1.5.4
