### ISSUE TITLE
SLOWNESS with vendor.js

### ISSUE THREAD

**Issue by AustinSaintAubin** [cheton/cnc#76]
I have noticed a major performance issue with my lower power workstations and mobile devices. 
Tested with Firefox and Chrome on Xubuntu 16.04 LTS, both had major preformance issues with CNC webpage.
Tested: http://threejs.org/examples/#webgl_multiple_renderers
- Firstfox showed some lag with webgl_multiple_renderers
- Chrome showed NO lag with webgl_multiple_renderers

Firefox Developer Tools Console:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendor.js:41:126
THREE.WebGLRenderer 78 vendor.js:26:25127
```

[preformace-profile.json.txt](https://github.com/cheton/cnc/files/468451/preformace-profile.json.txt)
---

Possible Solution Explanations / Related Issues:
- http://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance
- https://github.com/mrdoob/three.js/issues/9364

**Comment by AustinSaintAubin** [comment]
I think most of the performance issue is related to the preview rendering.
Anyway the preview widget could have the option to be disabled?
I would like to have the ability on tablets to disable the proview for performance reasons.

![screen shot 2016-09-15 at 5 30 17 pm](https://cloud.githubusercontent.com/assets/969780/18569743/3eef202a-7b6a-11e6-93c3-5ca7d076d50b.png)

**Comment by AustinSaintAubin** [comment]
Performance seems better as of v1.6.5

However, multiple devices do not sync current view.
Last device to connect get updates as CNC runs though gcode.

**Comment by cheton** [comment]
Related Issue: https://github.com/cheton/cnc/issues/33

**Comment by cheton** [comment]
This issue can be closed now since WebGL is no longer required by disabling 3D view in version 1.7.0.
Related issues: #33, #37, #86 

![image](https://cloud.githubusercontent.com/assets/447801/19961599/7c0af768-a1ee-11e6-8b4b-a3c628199af3.png)
