### ISSUE TITLE
UI scale on high dpi devices

### ISSUE THREAD

**Issue by liqdfire** [cheton/cnc#77]
I am running cnc.js on a 2046x1440 12 inch screen, and having the ability to control the UI scaling would be nice.

I am not familiar enough with Electron to just add it, but it looks like it supports controlling the scaling through the webview component.

**Comment by cheton** [comment]
The webContent object has methods for controlling zoom level: 
https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentssetzoomlevellevel

I will try to make the test and get back to you later.

**Comment by cheton** [comment]
Added in this commit d6a157e59c2f7e784026c73a0946c831ca24eed6

![image](https://cloud.githubusercontent.com/assets/447801/18556617/7d48c914-7b9e-11e6-9c58-8c3c6ff55da0.png)

I will publish a new version (v1.6.4) in the next few days that will contain the enhancement.

**Comment by liqdfire** [comment]
Outstanding, thank you!

**Comment by cheton** [comment]
Fixed v1.6.4
