### ISSUE TITLE
Bug: Cant Move Widgets

### ISSUE THREAD

**Issue by AustinSaintAubin** [cheton/cnc#79]
Cant move Widgets around on the page, attempting to move widget just highlights text.
Tested with fresh install v1.6.4 on Chrome, Firefox, Safari.

**Comment by cheton** [comment]
It's a code change side effects due to this commit 82bb9a6a0fd1a97183fc72d282e6abcdb707937c. I will fix it soon.

**Comment by cheton** [comment]
Fixed in v1.6.5
