### ISSUE TITLE
Layout Suggestion for Macro Widget

### ISSUE THREAD

**Issue by AustinSaintAubin** [cheton/cnc#80]
Could the Macro widget be edited to save a little space.
<img width="350" alt="screen shot 2016-09-16 at 10 42 17 pm" src="https://cloud.githubusercontent.com/assets/969780/18605715/3d02269a-7c5f-11e6-9656-66160ece954d.png">

I sujest moving the Add Macro to a function as a Cog or "+" on the top of the widget bar like the 
<img width="137" alt="screen shot 2016-09-16 at 10 45 26 pm" src="https://cloud.githubusercontent.com/assets/969780/18605717/4d748310-7c5f-11e6-8c0c-2c2d4b75e95a.png">

**Comment by cheton** [comment]
How about keeping the <kbd>Create Macro</kbd> button and the total records at the same line?

![image](https://cloud.githubusercontent.com/assets/447801/18606968/5b0de07e-7cf1-11e6-8ded-fd0c229ac807.png)

**Comment by cheton** [comment]
This commit 77b563a7cb23b99ecef7354e07d06872524f9e63 adds support for remembering widget minimized state. Now you can minimize rarely used widgets to save more space on UI.

![image](https://cloud.githubusercontent.com/assets/447801/18607316/416d0c66-7cfc-11e6-9e63-546bbd03ad36.png)

**Comment by cheton** [comment]
Fixed in v1.6.5

**Comment by AustinSaintAubin** [comment]
That works, is cleaner now.
