### ISSUE TITLE
Bug: Widget Minimis does not work

### ISSUE THREAD

**Issue by AustinSaintAubin** [cheton/cnc#81]
Unable to minimise widget after maximising. Chrome on Mac OS X, CNC v1.6.5
Issue seems to be affecting only the left column of widgets.
<img width="39" alt="screen shot 2016-09-17 at 2 55 44 pm" src="https://cloud.githubusercontent.com/assets/969780/18610641/f63c7e9e-7ce6-11e6-8102-848147959716.png">

**Comment by cheton** [comment]
Fixed in v1.6.6
