### ISSUE TITLE
Bugs: TinyWeb Connection Status & Coordinates 

### ISSUE THREAD

**Issue by AustinSaintAubin** [cheton/cnc#82]
[TinyWeb Example](https://github.com/cheton/cnc/tree/master/examples/tinyweb) needs some rework.

- Serial connection does not work unless another device has already opened the connection.
  - Connection status at top shows "Not connected", even when connection is technically established.
- Coordinates do not update.
- Does not display the current unit of measurement. (mm/in)

----- 

If possable it might be best to design TinyWeb to be a single widget loader. Where you can connect, to a selected widget.

**Comment by cheton** [comment]
Thanks for reporting this issue. There has been no changes over the past half year for the TinyWeb example, I will update the code to let it work again.  

The initial purpose when developing the TinyWeb example is just to provide a demo for showing how to communicate with the server with a simple UI. I may not spend much time on refining the sample code, but it's welcome for everyone to update the code by their own or send PRs to make changes.
