### ISSUE TITLE
Lessen Visibility of Completed Paths

### ISSUE THREAD

**Issue by AustinSaintAubin** [cheton/cnc#90]
It is difficult to visually make out the completed paths (RED) from the preloaded paths (RED) and to an extent the to be completed paths (BLUE).

I propose that once the path has been completed, its color is changed to GREY with a High Transparency. This would make it easy to see the preloaded paths (RED) and the to be completed paths (BLUE).

Picture bellow shows the issues... lot of RED, not sure which cut is coming next.
<img width="613" alt="screen shot 2016-10-25 at 6 54 23 pm" src="https://cloud.githubusercontent.com/assets/969780/19708569/180bf844-9ae5-11e6-91c5-a4c1d2094c94.png">

**Comment by cheton** [comment]
Thanks you for your suggestions. I will put the enhancements in v1.7.

**Comment by cheton** [comment]
Resolved in 1.7.0
