### ISSUE TITLE
new widget

### ISSUE THREAD

**Issue by eknap** [cheton/cnc#91]
How would a cnc pool widget

So a folder where g-code is located. Similar to the Macro widget.

Possibly a stimulus...

**Comment by cheton** [comment]
I think this is similar to #75: Add a live folder for watching G-code files. I will add this to the 1.8 milestone.

**Comment by cheton** [comment]
Implemented in the 1.8.5 release. You can see the usage at https://github.com/cheton/cnc/releases/tag/v1.8.5.
