### ISSUE TITLE
Shuttle express mac laptop

### ISSUE THREAD

**Issue by pfer** [cheton/cnc#93]
could you change ?  

Turn Jog Left
ctrl + alt + command + [
to 
ctrl + alt + command + (

Turn Jog Right
ctrl + alt + command + ]
to
ctrl + alt + command + )

can't reach [] with the shuttle app on mac laptop azerty ... as I already need a shortcut to reach it

**Comment by cheton** [comment]
All shortcut keys will be configurable in a future version. I can give you a custom build if you need it shortly.

**Comment by pfer** [comment]
good news ;) no need for a custom build, i borrowed an external qwerty keyboard to make my shuttle setup. Really nice software btw!
