### ISSUE TITLE
Firefox css issue on settings page (screenshot inside)

### ISSUE THREAD

**Issue by slimline33** [cheton/cnc#96]
Hi, there is an css error on firefox on the settings page...

![img_26112016-203757 1](https://cloud.githubusercontent.com/assets/3323812/20642768/3bc4a1b8-b418-11e6-8c2e-8b44c7d24ed9.jpg)

It is not importent but I wanted to share it :)

**Comment by slimline33** [comment]
Found another view issue on the probe widget:

![img_26112016-204139 1](https://cloud.githubusercontent.com/assets/3323812/20642787/e7f5bd46-b418-11e6-8896-13ef5c616e10.jpg)

**Comment by cheton** [comment]
I just resolved the css problem in the <b>Settings</b> page, but I cannot reproduce the issue on the probe widget. May I know which cnc and firefox versions you're running on what platform? Thanks.

**Comment by slimline33** [comment]
mhmm... after clearing browser cache the widget is o.k

![img_27112016-161134 1](https://cloud.githubusercontent.com/assets/3323812/20649283/2e6696a8-b4bc-11e6-911e-cc8f46f14ebd.jpg)

thanks!

Firefox 50.0 on Windows7 64bit
