### ISSUE TITLE
Update the raspberry kernel to beta in installation guide

### ISSUE THREAD

**Issue by slimline33** [cheton/cnc#97]
Hi!

I think it is not good to tell the user to update the raspberry kernel with sudo rpi-update.
Thats always nightly kernels and there could be the one or the other bug in.

Here: https://github.com/cheton/cnc/wiki/Raspberry-Pi-Setup-Guide#maintaining-your-software-stack-w-updates--upgrades

Just use apt-get update / upgrade. That will also update the kernel to a stable version!

Source: https://www.elektronik-kompendium.de/sites/raspberry-pi/2006061.htm (german only)

Thanks

Christoph

**Comment by cheton** [comment]
Loop @AustinSaintAubin

**Comment by AustinSaintAubin** [comment]
Updated wiki documentation regarding Raspberry Pi setup and updates.
github.com/cheton/cnc/wiki/Raspberry-Pi-Setup-Guide

**Comment by cheton** [comment]
Great! Thanks.

**Comment by slimline33** [comment]
Nice work! Thanks!
