### ISSUE TITLE
Error: WARN deprecated stack-generator@1.1.0

### ISSUE THREAD

**Issue by slimline33** [cheton/cnc#98]
Hi, today I wanted to update cncjs but it stops with the following error:

`npm WARN deprecated stack-generator@1.1.0: Includes breaking dependency change. Please update to v2.0.0`
`/usr/bin/cnc -> /usr/lib/node_modules/cncjs/bin/cnc`
`/usr/lib`
`└─┬ cncjs@1.8.3`
`  └── UNMET PEER DEPENDENCY sortablejs@1.5.0-rc1`

`npm WARN react-sortablejs@1.1.2 requires a peer of sortablejs@1.x but none was installed.`

What can I do? 🗡

**Comment by cheton** [comment]
I just made an update in react-sortablejs to use sortablejs@1.5.0-rc1 as its peerDependencies, but I forgot to update react-sortablejs to v1.2.0 in cncjs's package.json file. I will fix it soon.
